#include "fake-wled.h"
#include "loo_ddp.h"
#include "loo_dma_status.h"

#include <algorithm>
#include <array>
#include <cassert>
#include <cstdint>
#include <map>
#include <vector>

struct e131_packet_t { uint8_t bytes[1]; };

byte realtimeMode = REALTIME_MODE_INACTIVE;
byte realtimeOverride = REALTIME_OVERRIDE_NONE;
uint32_t realtimeTimeout = 0;
uint32_t realtimeTimeoutMs = 1000;
IPAddress realtimeIP;
bool useMainSegmentOnly = true;
byte bri = 128;
byte briT = 128;
byte briLast = 128;
bool arlsForceMaxBri = false;
bool e131NewData = false;
bool udpConnected = false;
unsigned notificationCount = 0;
unsigned udpNumRetries = 0;
uint32_t notificationSentTime = 0;
byte notificationSentCallMode = 0;
uint16_t DMXAddress = 0;
int arlsOffset = 0;
FakeStrip strip;
std::map<std::string, uint32_t> jsonValues;
std::atomic<uint32_t> loo_dma_requested{0};
std::atomic<uint32_t> loo_dma_active_lanes{0};
std::atomic<uint32_t> loo_dma_failure{0};
std::atomic<uint32_t> loo_dma_required{0};
std::atomic<uint32_t> loo_dma_free_before{0};
std::atomic<uint32_t> loo_dma_largest_before{0};
std::atomic<uint32_t> loo_dma_allocated{0};
std::atomic<uint32_t> loo_dma_descriptors{0};

static uint32_t nowUs = 0;
static uint32_t busyUntilUs = 0;
static unsigned exits = 0;

static bool actualShowPrefix();
static void actualShowSuffix();
static void actualNotificationPrefix();

uint32_t micros() { return nowUs; }
uint32_t millis() { return nowUs / 1000; }

namespace BusManager {
bool canAllShow() { return uint32_t(nowUs - busyUntilUs) < 0x80000000u; }
void show() { busyUntilUs = nowUs + 21420; }
}

void notify(byte, bool) {}
void updateInterfaces(byte) { ++exits; }

void FakeStrip::show() {
  if (suspendBeforeShow) suspended = true;
  if (rejectShow || !actualShowPrefix()) return;
  nowUs += paintUs;
  std::vector<byte> wire(length * 3);
  for (size_t logicalIndex = 0; logicalIndex < length; ++logicalIndex) {
    const auto physical = map[logicalIndex];
    wire[physical * 3] = logical[logicalIndex][0];
    wire[physical * 3 + 1] = logical[logicalIndex][1];
    wire[physical * 3 + 2] = logical[logicalIndex][2];
  }
  wireSnapshots.push_back(std::move(wire));
  actualShowSuffix();
  lastShowMs = millis();
}

// Generated by test-service.py from the patched e131.cpp receiver body.
#include "extracted-ddp-handler.inc"
// Generated by test-service.py from udp.cpp and FX_fcn.cpp.
#include "extracted-lifecycle.inc"

static std::vector<uint8_t> packet(size_t offset, size_t count, uint8_t sequence,
                                   bool push, uint8_t value) {
  std::vector<uint8_t> bytes(10 + count, value);
  bytes[0] = push ? 0x41 : 0x40;
  bytes[1] = sequence;
  bytes[2] = 0x0b;
  bytes[3] = 1;
  bytes[4] = byte(offset >> 24);
  bytes[5] = byte(offset >> 16);
  bytes[6] = byte(offset >> 8);
  bytes[7] = byte(offset);
  bytes[8] = byte(count >> 8);
  bytes[9] = byte(count);
  return bytes;
}

static void receiveFrame(uint8_t value, uint32_t sender, bool push = true,
                         size_t omitOffset = SIZE_MAX) {
  uint8_t sequence = 1;
  const size_t total = strip.length * 3;
  for (size_t offset = 0; offset < total; offset += 1440) {
    const size_t count = std::min<size_t>(1440, total - offset);
    if (offset != omitOffset) {
      auto bytes = packet(offset, count, sequence, push && offset + count == total, value);
      handleDDPPacket(reinterpret_cast<e131_packet_t*>(bytes.data()), bytes.size(), IPAddress(sender));
    }
    sequence = sequence == 15 ? 1 : uint8_t(sequence + 1);
  }
}

static std::array<uint8_t, 3> indexedRgb(size_t logical) {
  return {uint8_t(logical), uint8_t(logical >> 8), uint8_t(0xa5 ^ logical)};
}

static void receiveIndexedFrame(uint32_t sender) {
  uint8_t sequence = 1;
  const size_t total = strip.length * 3;
  for (size_t offset = 0; offset < total; offset += 1440) {
    const size_t count = std::min<size_t>(1440, total - offset);
    auto bytes = packet(offset, count, sequence, offset + count == total, 0);
    for (size_t byteIndex = 0; byteIndex < count; byteIndex += 3) {
      const auto color = indexedRgb((offset + byteIndex) / 3);
      bytes[10 + byteIndex] = color[0];
      bytes[10 + byteIndex + 1] = color[1];
      bytes[10 + byteIndex + 2] = color[2];
    }
    handleDDPPacket(reinterpret_cast<e131_packet_t*>(bytes.data()), bytes.size(), IPAddress(sender));
    sequence = sequence == 15 ? 1 : uint8_t(sequence + 1);
  }
}

static void notificationPrefix(bool nativeDue = true) {
  actualNotificationPrefix();
  if (nativeDue && (realtimeMode != REALTIME_MODE_DDP || realtimeOverride)) {
    ++strip.nativeServices;
    strip.show();
  }
}

static uint32_t stat(const char* key) {
  looDdpJson({});
  return jsonValues[key];
}

static void setup() {
  looDdpReset();
  nowUs = 0;
  busyUntilUs = 0;
  exits = 0;
  realtimeMode = REALTIME_MODE_INACTIVE;
  realtimeOverride = REALTIME_OVERRIDE_NONE;
  realtimeTimeout = 0;
  realtimeTimeoutMs = 1000;
  useMainSegmentOnly = true;
  strip = {};
  strip.length = 2624;
  strip.logical.assign(strip.length, {0, 0, 0});
  strip.map.resize(strip.length);
  for (size_t i = 0; i < strip.length; ++i) strip.map[i] = uint16_t((i * 733) % strip.length);
  loo_dma_requested = 0;
  loo_dma_active_lanes = 0;
  loo_dma_failure = 0;
  DMXAddress = 0;
  arlsOffset = 0;
  jsonValues.clear();
  // The current service configures storage before the UDP receiver runs.
  looDdpService();
}

static void advance(uint32_t us) { nowUs += us; }

int main() {
  setup();
  receiveIndexedFrame(0x01020304);
  notificationPrefix(false);
  assert(strip.wireSnapshots.size() == 1);
  for (size_t logicalIndex = 0; logicalIndex < strip.length; ++logicalIndex) {
    const auto color = indexedRgb(logicalIndex);
    const auto physical = strip.map[logicalIndex];
    const auto& wire = strip.wireSnapshots.back();
    assert(wire[physical * 3] == color[0]);
    assert(wire[physical * 3 + 1] == color[1]);
    assert(wire[physical * 3 + 2] == color[2]);
  }

  setup();
  DMXAddress = 6;
  arlsOffset = 3;
  receiveIndexedFrame(0x01020304);
  notificationPrefix(false);
  assert(strip.wireSnapshots.size() == 1 && strip.realtimeWrites == strip.length - 5);
  for (size_t logicalIndex = 0; logicalIndex < strip.length; ++logicalIndex) {
    const auto& wire = strip.wireSnapshots.back();
    const auto physical = strip.map[logicalIndex];
    const auto color = logicalIndex < 5
      ? std::array<uint8_t, 3>{0, 0, 0}
      : indexedRgb(logicalIndex - 5);
    assert(wire[physical * 3] == color[0]);
    assert(wire[physical * 3 + 1] == color[1]);
    assert(wire[physical * 3 + 2] == color[2]);
  }

  setup();
  const auto presentedBefore = stat("presented");
  const auto completedBefore = stat("tx_completed");
  receiveFrame(0x11, 0x01020304);
  notificationPrefix(false);
  assert(strip.wireSnapshots.size() == 1);
  assert(realtimeMode == REALTIME_MODE_DDP && strip.main.freeze);
  assert(strip.main.stoppedTransitions == 1);
  assert(stat("presented") == presentedBefore + 1 && stat("tx_completed") == completedBefore);
  const auto first = strip.wireSnapshots.back();
  assert(first[strip.map[0] * 3] == 0x11 && first[strip.map[1] * 3 + 2] == 0x11);
  receiveFrame(0x22, 0x01020304);
  notificationPrefix(false);
  assert(strip.wireSnapshots.size() == 1 && strip.wireSnapshots.front() == first);
  advance(21420);
  notificationPrefix(false);
  assert(strip.wireSnapshots.size() == 2 && strip.wireSnapshots.back()[strip.map[9] * 3] == 0x22);
  assert(stat("presented") == presentedBefore + 2 && stat("tx_completed") == completedBefore + 1);

  setup();
  receiveFrame(0x33, 7, true, 1440);
  notificationPrefix(false);
  assert(strip.wireSnapshots.empty() && realtimeMode == REALTIME_MODE_INACTIVE);
  advance(100001);
  auto invalid = packet(0, 3, 1, true, 0x44);
  handleDDPPacket(reinterpret_cast<e131_packet_t*>(invalid.data()), invalid.size(), IPAddress(7));
  notificationPrefix(false);
  assert(strip.wireSnapshots.empty());

  setup();
  receiveFrame(0x45, 7);
  notificationPrefix(false);
  advance(21420);
  receiveFrame(0x46, 7, true, 1440);
  notificationPrefix(false);
  const auto showsBeforeTimeout = strip.wireSnapshots.size();
  advance(1000001);
  notificationPrefix();
  assert(strip.wireSnapshots.size() == showsBeforeTimeout + 1);
  assert(realtimeMode == REALTIME_MODE_INACTIVE && strip.nativeServices == 1);

  setup();
  receiveFrame(0x51, 8);
  notificationPrefix(false);
  receiveFrame(0x52, 8);
  receiveFrame(0x53, 8);
  advance(21420);
  notificationPrefix(false);
  assert(strip.wireSnapshots.size() == 2);
  assert(strip.wireSnapshots.back()[strip.map[100] * 3] == 0x53);

  setup();
  strip.paintUs = 5000;
  for (unsigned frame = 0; frame < 30; ++frame) {
    receiveFrame(uint8_t(frame), 9);
    notificationPrefix(false);
    advance(33333 - 5000);
    notificationPrefix(false);
  }
  assert(strip.wireSnapshots.size() == 30);

  setup();
  strip.paintUs = 5000;
  receiveFrame(0, 10);
  notificationPrefix(false);
  nowUs = 25000;
  receiveFrame(1, 10);
  notificationPrefix(false);
  receiveFrame(39, 10);
  nowUs = 26420;
  notificationPrefix(false);
  assert(strip.wireSnapshots.size() == 2);
  assert(strip.wireSnapshots.back()[strip.map[3] * 3] == 39 && stat("superseded") >= 1);

  setup();
  strip.pixelsAvailable = false;
  receiveFrame(0x54, 10);
  notificationPrefix(false);
  assert(strip.realtimeWrites == 0 && strip.wireSnapshots.empty() && stat("paint_blocked") >= 1);

  setup();
  strip.suspended = true;
  receiveFrame(0x55, 10);
  notificationPrefix(false);
  assert(strip.realtimeWrites == 0 && strip.wireSnapshots.empty());
  strip.suspended = false;
  receiveFrame(0x56, 10);
  notificationPrefix(false);
  assert(strip.wireSnapshots.size() == 1 && strip.wireSnapshots.back()[strip.map[2] * 3] == 0x56);

  setup();
  strip.suspendBeforeShow = true;
  receiveFrame(0x57, 10);
  notificationPrefix(false);
  assert(strip.realtimeWrites == strip.length && strip.wireSnapshots.empty() && !strip.servicing);
  strip.suspendBeforeShow = false;
  strip.suspended = false;
  receiveFrame(0x58, 10);
  notificationPrefix(false);
  assert(strip.wireSnapshots.size() == 1 && !strip.servicing);

  setup();
  useMainSegmentOnly = false;
  receiveFrame(0x59, 10);
  notificationPrefix(false);
  assert(strip.wireSnapshots.size() == 1 && !strip.main.freeze);

  setup();
  receiveFrame(0x61, 11);
  notificationPrefix(false);
  assert(strip.wireSnapshots.size() == 1);
  advance(21420);
  exitRealtime();
  assert(exits == 1 && realtimeMode == REALTIME_MODE_INACTIVE);
  notificationPrefix();
  assert(strip.nativeServices == 1);

  setup();
  receiveFrame(0x62, 12);
  notificationPrefix(false);
  realtimeOverride = 2;
  notificationPrefix();
  assert(realtimeMode == REALTIME_MODE_DDP && strip.nativeServices == 1);
  realtimeOverride = REALTIME_OVERRIDE_NONE;
  exitRealtime();

  setup();
  receiveFrame(0x71, 13);
  notificationPrefix(false);
  const auto abortedBeforeReset = stat("tx_aborted_or_unobserved");
  looDdpReset();
  looDdpReset();
  assert(stat("tx_aborted_or_unobserved") == abortedBeforeReset + 1);
  advance(21420);
  notificationPrefix(false);

  setup();
  strip.rejectShow = true;
  receiveFrame(0x72, 14);
  notificationPrefix(false);
  assert(strip.wireSnapshots.empty());

  setup();
  loo_dma_requested = 1;
  loo_dma_failure = 2;
  realtimeLock(1000, REALTIME_MODE_DDP);
  receiveFrame(0x73, 15);
  notificationPrefix(false);
  assert(strip.wireSnapshots.empty() && realtimeMode == REALTIME_MODE_INACTIVE && exits == 1);
}
